[build]
  base = "/"
  publish = "build"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[build.environment]
  supabase_db_POSTGRES_URL = "postgres://postgres.koxcwjscznanhqukepav:h2RqGp9eyYeVQWTV@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&supa=base-pooler.x"
  supabase_db_POSTGRES_PRISMA_URL = "postgres://postgres.koxcwjscznanhqukepav:h2RqGp9eyYeVQWTV@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&supa=base-pooler.x"
  supabase_db_SUPABASE_URL = "https://koxcwjscznanhqukepav.supabase.co"
  supabase_db_NEXT_PUBLIC_SUPABASE_URL = "https://koxcwjscznanhqukepav.supabase.co"
  supabase_db_POSTGRES_URL_NON_POOLING = "postgres://postgres.koxcwjscznanhqukepav:h2RqGp9eyYeVQWTV@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require"
  supabase_db_SUPABASE_JWT_SECRET = "vfnr3dZJcNlWLyndvzllyb9GZaUy8aBKsMpEAG/LRBGsPys7+d95j3EU7YEcURKWp4kZbHB/JebIa15noeC9KQ=="
  supabase_db_POSTGRES_USER = "postgres"
  supabase_db_NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtveGN3anNjem5hbmhxdWtlcGF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzODEzNjMsImV4cCI6MjA1Mzk1NzM2M30.JvaEPb_BADxdhSoNt6WmbLH3ckkHTtM_1skkS5c8Hq4"
  supabase_db_POSTGRES_PASSWORD = "h2RqGp9eyYeVQWTV"
  supabase_db_POSTGRES_DATABASE = "postgres"
  supabase_db_SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtveGN3anNjem5hbmhxdWtlcGF2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczODM4MTM2MywiZXhwIjoyMDUzOTU3MzYzfQ.RBLQcoP5eWpb-PmZLgh6AH86hs62j4QzMoxAEcy_vGU"
  supabase_db_POSTGRES_HOST = "db.koxcwjscznanhqukepav.supabase.co"
